---
name: continuous-integration

on: [push, pull_request]

jobs:

    test-package:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10', '3.11']

        steps:

            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install package
              run: |
                  python -m pip install .[pre_commit,tests]

            - name: Run pre-commit
              run: |
                  pre-commit run --all-files

            - name: Run tests
              run: python -m pytest -v
